version: "3.9"

services:
  postgres:
    image: postgres:16.1-alpine
    env_file: .env
    volumes:
      - ./data/postgres/:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
