spring:
  application:
    name: library-management-system
  datasource:
    url: jdbc:postgresql://localhost:5432/lms
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect  # Correct dialect
  flyway:
    baseline-on-migrate: true
    enable: true
    user: postgres
    password: password
    baseline-description: "init"
    baseline-version: 0
